import { BookMeta } from './types';

const R2_BASE = 'https://pub-53f9bd2475cc48ccbcb450df64234f24.r2.dev';

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 80);
}

function toFilename(author: string, title: string): string {
  const a = author.split('&')[0].trim().replace(/\s+/g, '_');
  const t = title.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
  return `${a}_-_${t}.pdf`;
}

// Raw book data from the African Literature collection
const rawBooks: Array<{ author: string; title: string; coverImage?: string }> = [
  { author: 'Agnes Sam', title: 'Jesus Is Indian and Other Stories', coverImage: '/covers/jesus-is-indian.png' },
  { author: 'Ahmadou Kourouma', title: 'The Suns of Independence', coverImage: '/covers/the-suns-of-independence.png' },
  { author: 'Albert W. Kayper-Mensah', title: 'The Drummer in Our Time Poems', coverImage: '/covers/the-drummer-in-our-time.png' },
  { author: 'Alex La Guma', title: 'A Walk in the Night and other Stories', coverImage: '/covers/a-walk-in-the-night.png' },
  { author: 'Alex La Guma', title: 'In the Fog of the Seasons\' End' },
  { author: 'Alex La Guma', title: 'Time of the Butcherbird' },
  { author: 'Ali Jahadmy & Ali Ahmed Jahadhmy & Ali Jahadhmy', title: 'Anthology of Swahili Poetry' },
  { author: 'Amechi Nicholas Akwanya', title: 'Orimili' },
  { author: 'Amílcar Cabral', title: 'Unity Struggle: Selected Speeches and Writings' },
  { author: 'Amu Djoleto', title: 'The Strange Man' },
  { author: 'Angus Calder', title: 'Summer Fires: New Poetry of Africa' },
  { author: 'Asare Konadu', title: 'A Woman in Her Prime' },
  { author: 'Asare Konadu & Samuel Asare Konadu', title: 'Ordained by the Oracle' },
  { author: 'Aubrey Kachingwe', title: 'No Easy Task' },
  { author: 'Ayi Kwei Armah', title: 'The Beautyful Ones Are Not Yet Born' },
  { author: 'Barry Feinberg', title: 'Poets to the People: South African Freedom Poems' },
  { author: 'Benjamin Kwakye', title: 'The Clothes of Nakedness' },
  { author: 'Bernard Binlin Dadié', title: 'Climbié' },
  { author: 'Bessie Head', title: 'A Woman Alone: Autobiographical Writings' },
  { author: 'Bessie Head', title: 'Maru' },
  { author: 'Bessie Head', title: 'Serowe: Village of the Rainwind' },
  { author: 'Bessie Head', title: 'Tales of Tenderness and Power' },
  { author: 'Bessie Head', title: 'The Cardinals' },
  { author: 'Bessie Head', title: 'The Collector of Treasures and Other Botswana Village Tales' },
  { author: 'Binwell Sinyangwe', title: 'A Cowrie of Hope' },
  { author: 'Biyi Bandele-Thomas', title: 'The Sympathetic Undertaker and Other Dreams' },
  { author: 'Buchi Emecheta', title: 'Destination Biafra' },
  { author: 'Buchi Emecheta', title: 'The Family' },
  { author: 'Buchi Emecheta', title: 'The New Tribe' },
  { author: 'Can Themba', title: 'The Will to Die' },
  { author: 'Charlotte H. Bruner', title: 'The Heinemann Book of African Women\'s Writing' },
  { author: 'Cheikh Hamidou Kane', title: 'Ambiguous Adventure' },
  { author: 'Chenjerai Hove', title: 'Bones' },
  { author: 'Chinua Achebe', title: 'Heinemann Book of Contemporary African Short Stories' },
  { author: 'Chinua Achebe & C. L. Innes', title: 'African Short Stories (African Writers Series)' },
  { author: 'Cosmo Pieterse', title: 'Five African Plays' },
  { author: 'Cosmo Pieterse', title: 'Seven South African Poets: Poems of Exile' },
  { author: 'Cosmo Pieterse', title: 'Short African Plays' },
  { author: 'Cosmo Pieterse', title: 'Ten One-Act Plays' },
  { author: 'Cyprian Ekwensi', title: 'Restless City and Christmas Gold with Other Stories' },
  { author: 'Cyprian Ekwensi', title: 'Survive the Peace' },
  { author: 'D. M. Zwelonke', title: 'Robben Island' },
  { author: 'Dambudzo Marechera', title: 'Black Sunlight' },
  { author: 'Dambudzo Marechera', title: 'The House of Hunger' },
  { author: 'Daniachew Worku & Däñäčaw Warqu', title: 'The Thirteenth Sun' },
  { author: 'Daniel M. Mengara', title: 'Mema' },
  { author: 'David & Lee Cook', title: 'Short East African Plays in English' },
  { author: 'David Cook', title: 'Origin East Africa: A Makerere Anthology' },
  { author: 'David Cook & David Rubadiri', title: 'Poems From East Africa' },
  { author: 'Denis Hirson & Martin Trump', title: 'The Heinemann Book of South African Short Stories' },
  { author: 'Dennis Brutus', title: 'A Simple Lust: Selected Poems' },
  { author: 'Denys Johnson-Davies', title: 'Egyptian Short Stories' },
  { author: 'Dominic Mulaisho', title: 'The Smoke That Thunders' },
  { author: 'Dominic Mulaisho', title: 'The Tongue of the Dumb' },
  { author: 'Donatus Nwoga', title: 'Igbo Traditional Verse (African Writers Series)' },
  { author: 'Doris Lessing', title: 'The Grass Is Singing' },
  { author: 'Driss Chraïbi', title: 'Heirs to the Past' },
  { author: 'E. E. Sule', title: 'Sterile Sky' },
  { author: 'Eddie Iroh', title: 'Forty-Eight Guns for the General' },
  { author: 'Eddie Iroh', title: 'Toads of War' },
  { author: 'Elechi Amadi', title: 'Estrangement' },
  { author: 'Elechi Amadi', title: 'Sunset in Biafra: A Civil War Diary' },
  { author: 'Elechi Amadi', title: 'The Great Ponds' },
  { author: 'Elechi Amadi', title: 'The Slave' },
  { author: 'Evelyne Accad', title: 'Wounding Words: A Woman\'s Journal in Tunisia' },
  { author: 'Farida Karodia', title: 'A Shattering of Silence' },
  { author: 'Farida Karodia', title: 'Coming Home and Other Stories' },
  { author: 'Fathī Ghānim', title: 'The Man Who Lost His Shadow: A Novel in Four Books' },
  { author: 'Ferdinand Oyono', title: 'Houseboy' },
  { author: 'Ferdinand Oyono', title: 'The Old Man and the Medal' },
  { author: 'Flora Nwapa', title: 'Idu' },
  { author: 'Francis Bebey', title: 'Agatha Moudio\'s Son' },
  { author: 'Francis Bebey', title: 'The Ashanti Doll' },
  { author: 'Francis Selormey', title: 'The Narrow Path: An African Childhood' },
  { author: 'Gabriel Okara', title: 'The Voice' },
  { author: 'Gaele Sobott-Mogwe', title: 'Colour Me Blue' },
  { author: 'Gwyneth Henderson', title: 'African Theatre: Eight Prize-Winning Plays for Radio' },
  { author: 'Gwyneth Henderson', title: 'Nine African Plays for Radio' },
  { author: 'Ham Mukasa', title: 'Uganda\'s Katikiro in England' },
  { author: 'Hama Tuma', title: 'The Case of the Socialist Witchdoctor and Other Stories' },
  { author: 'Henri Lopes', title: 'Tribaliks: Contemporary Congolese Stories' },
  { author: 'Hugh Lewin', title: 'Bandiet Out of Jail: Seven Years in a South African Prison' },
  { author: 'I. N. C. Aniebo', title: 'Of Wives Talismans and the Dead' },
  { author: 'I. N. C. Aniebo', title: 'The Anonymity of Sacrifice' },
  { author: 'I. N. C. Aniebo', title: 'The Journey Within' },
  { author: 'Jack Mapanje', title: 'Of Chameleons and Gods' },
  { author: 'Jack Mapanje', title: 'The Chattering Wagtails of Mikuyu Prison' },
  { author: 'Jamal Mahjoub', title: 'In the Hour of Signs' },
  { author: 'Jamal Mahjoub', title: 'Wings of Dust' },
  { author: 'Jared Angira', title: 'Silent Voices: Poems' },
  { author: 'Joe De Graft', title: 'Beneath the Jazz and Brass' },
  { author: 'John Munonye', title: 'Bridge to a Wedding' },
  { author: 'John Munonye', title: 'Obi' },
  { author: 'John Nagenda', title: 'The Seasons of Thomas Tebo' },
  { author: 'John O. Reed & Clive Wake', title: 'A Book of African Verse: The Well-Known Anthology' },
  { author: 'John Okechukwu Munonye', title: 'A Dancer of Fortune' },
  { author: 'John Okechukwu Munonye', title: 'A Wreath for the Maidens' },
  { author: 'John Okechukwu Munonye', title: 'Oil Man of Obange' },
  { author: 'John Reed', title: 'French African Verse (African Writers Series)' },
  { author: 'John Ya-Otto & Ole Gjerstad & Michael Mercer', title: 'Battlefront Namibia: An Autobiography' },
  { author: 'Jomo Kenyatta', title: 'Facing Mount Kenya: The Traditional Life of the Gikuyu' },
  { author: 'José Luandino Vieira', title: 'The Real Life of Domingos Xavier' },
  { author: 'José Luandino Vieira & José Vieira Mateus Da Graça', title: 'Luuanda: Short Stories of Angola' },
  { author: 'Kenneth D. Kaunda', title: 'Zambia Shall Be Free: An Autobiography' },
  { author: 'Kofi Anyidoho', title: 'A Harvest of Our Dreams With Elegy for the Revolution' },
  { author: 'Kofi Awoonor', title: 'This Earth My Brother' },
  { author: 'Kofi Awoonor & G. Adali-Mortty', title: 'Messages: Poems From Ghana' },
  { author: 'Kole Omotoso', title: 'The Combat' },
  { author: 'Lawrence Vambe', title: 'An Ill-Fated People: Zimbabwe Before and After Rhodes' },
  { author: 'Leila Aboulela', title: 'The Translator' },
  { author: 'Len Ortzen', title: 'North African Writing' },
  { author: 'Lenrie Peters', title: 'Katchikali' },
  { author: 'Lenrie Peters', title: 'Satellites' },
  { author: 'Lenrie Peters', title: 'Selected Poetry' },
  { author: 'Lilia Momplé', title: 'Neighbours: The Story of a Murder' },
  { author: 'Luís Bernardo Honwana', title: 'We Killed Mangy-Dog & Other Mozambique Stories' },
  { author: 'M. G. Vassanji', title: 'The Gunny Sack' },
  { author: 'M. G. Vassanji', title: 'Uhuru Street: Short Stories' },
  { author: 'Malum Amadu & Gulla Kell', title: 'Amadu\'s Bundle: Fulani Tales of Love and Djinns' },
  { author: 'Mariama Bâ', title: 'So Long a Letter' },
  { author: 'Martha Mvungi', title: 'Three Solid Stones' },
  { author: 'Mazisi Kunene', title: 'Emperor Shaka the Great: A Zulu Epic' },
  { author: 'Mbella Sonne Dipoko', title: 'A Few Nights and Days' },
  { author: 'Mbella Sonne Dipoko', title: 'Black & White in Love: Poems' },
  { author: 'Meja Mwangi', title: 'Baba Pesa: Striving for the Wind' },
  { author: 'Meja Mwangi', title: 'Carcase for Hounds' },
  { author: 'Meja Mwangi', title: 'Going Down River Road' },
  { author: 'Mia Couto', title: 'Every Man Is a Race' },
  { author: 'Mia Couto', title: 'Voices Made Night' },
  { author: 'Michael Etherton', title: 'African Plays for Playing' },
  { author: 'Modikwe Dikobe', title: 'The Marabi Dance' },
  { author: 'Molefe Pheto', title: 'And Night Fell: Memoirs of a Political Prisoner in South Africa' },
  { author: 'Mongane Wally Serote', title: 'Selected Poems' },
  { author: 'Mongane Wally Serote', title: 'To Every Birth Its Blood: A Novel' },
  { author: 'Mongo Beti', title: 'King Lazarus' },
  { author: 'Mongo Beti', title: 'The Poor Christ of Bomba' },
  { author: 'Mothobi', title: 'Africa South Contemporary Writings' },
  { author: 'Mukotani Rugyendo', title: 'The Barbed Wire & Other Plays' },
  { author: 'Musaemura Zimunya & Peter Porter & Kofi Anyidoho', title: 'Fate of Vultures: New Poetry of Africa' },
  { author: 'Mwangi Ruheni', title: 'The Future Leaders' },
  { author: 'Nadine Gordimer', title: 'Crimes of Conscience' },
  { author: 'Nadine Gordimer', title: 'Some Monday for Sure' },
  { author: 'Naguib Mahfouz', title: 'Midaq Alley' },
  { author: 'Najib Mahfūz', title: 'Children of Gebelawi' },
  { author: 'Najib Mahfūz & Naguib Mahfouz', title: 'Miramar' },
  { author: 'Nelson Mandela', title: 'No Easy Walk to Freedom' },
  { author: 'Neshani Andreas', title: 'The Purple Violet of Oshaantu' },
  { author: 'Ngugi wa Thiong\'o', title: 'Secret Lives & Other Stories' },
  { author: 'Ngugi wa Thiong\'o', title: 'The Trial of Dedan Kimathi' },
  { author: 'Ngũgĩ Wa Thiong\'o', title: 'Weep Not Child' },
  { author: 'Niyi Osundare', title: 'Selected Poems' },
  { author: 'Nkem Nwankwo', title: 'Danda' },
  { author: 'Nkem Nwankwo', title: 'My Mercedes Is Bigger Than Yours' },
  { author: 'Nuruddin Farah', title: 'From a Crooked Rib' },
  { author: 'Nuruddin Farah', title: 'Sardines' },
  { author: 'Nuruddin Farah', title: 'Sweet and Sour Milk' },
  { author: 'Obotunde Ijimere', title: 'The Imprisonment of Obatala & Other Plays' },
  { author: 'Oginga Odinga', title: 'Not Yet Uhuru: The Autobiography of Oginga Odinga' },
  { author: 'Okot p\'Bitek', title: 'Hare and Hornbill' },
  { author: 'Okot p\'Bitek', title: 'The Horn of My Love' },
  { author: 'Olaudah Equiano', title: 'Equiano\'s Travels' },
  { author: 'Oliver Tambo', title: 'Preparing for Power: Oliver Tambo Speaks' },
  { author: 'Onuora Nzekwu', title: 'Blade Among the Boys' },
  { author: 'Onuora Nzekwu', title: 'Wand of Noble Wood' },
  { author: 'Ousmane Sembène', title: 'Black Docker' },
  { author: 'Ousmane Sembène', title: 'God\'s Bits of Wood' },
  { author: 'Ousmane Sembène', title: 'Niiwam and Taaw' },
  { author: 'Ousmane Sembène', title: 'Taaw' },
  { author: 'Ousmane Sembène', title: 'The Money Order: With White Genesis' },
  { author: 'Paul A. Scanlon', title: 'Stories From Central & Southern Africa' },
  { author: 'Paul Breman', title: 'You Better Believe It: Black Verse in English' },
  { author: 'Pepetela', title: 'Mayombe' },
  { author: 'Peter Abrahams', title: 'Mine Boy' },
  { author: 'Peter Kishili Palangyo', title: 'Dying in the Sun' },
  { author: 'R. L. Peteni', title: 'Hill of Fools' },
  { author: 'R. Mugo Gatheru', title: 'Child of Two Worlds: A Kikuyu\'s Story' },
  { author: 'Rayda Jacobs', title: 'Eyes of the Sky' },
  { author: 'René Maran', title: 'Batouala' },
  { author: 'Réshard Gool', title: 'Cape Town Coolie' },
  { author: 'Richard Rive', title: 'Buckingham Palace District Six' },
  { author: 'Richard Rive', title: 'Modern African Prose' },
  { author: 'Richard Rive', title: 'Quartet New Voices From South Africa' },
  { author: 'Rifat Alifah', title: 'Distant View of a Minaret & Other Stories' },
  { author: 'Robert Serumaga', title: 'Return to the Shadows' },
  { author: 'Sahle Sellassie', title: 'The Afersata: An Ethiopian Novel' },
  { author: 'Sahle Sellassie', title: 'Warrior King' },
  { author: 'Samuel Kahiga', title: 'The Girl From Abroad' },
  { author: 'Sebastian Okechukwu Mezu', title: 'Behind the Rising Sun' },
  { author: 'Shimmer Chinodya', title: 'Can We Talk and Other Stories' },
  { author: 'Shimmer Chinodya', title: 'Dew in the Morning' },
  { author: 'Shimmer Chinodya', title: 'Harvest of Thorns' },
  { author: 'Sol T. Plaatje', title: 'Mhudi' },
  { author: 'Sony Lab\'Ou Tansi', title: 'The Seven Solitudes of Lorsa Lopez' },
  { author: 'Stanlake Samkange', title: 'On Trial for My Country' },
  { author: 'Stanlake Samkange & John Thompson', title: 'Year of the Uprising' },
  { author: 'Stanley Nyamfukudza', title: 'The Non-Believer\'s Journey' },
  { author: 'Stella Chipasula', title: 'The Heinemann Book of African Women\'s Poetry' },
  { author: 'Steve Jacobs', title: 'The Enemy Within' },
  { author: 'Steve Jacobs', title: 'Under the Lion' },
  { author: 'Syl Cheney-Coker', title: 'Concerto for an Exile: Poems' },
  { author: 'Syl Cheney-Coker', title: 'The Graveyard Also Has Teeth: With Concerto for an Exile' },
  { author: 'T. M. Aluko', title: 'Chief the Honourable Minister' },
  { author: 'T. M. Aluko', title: 'His Worshipful Majesty' },
  { author: 'T. M. Aluko', title: 'Kinsman and Foreman' },
  { author: 'T. M. Aluko', title: 'Wrong Ones in the Dock' },
  { author: 'T. M. Aluko & Timothy Mofolorunso Aluko & Mof Olorunso Aluko', title: 'One Man One Matchet' },
  { author: 'T. Obinkaram Echewa', title: 'The Crippled Dancer' },
  { author: 'Taban Lo Liyong', title: 'Another Nigger Dead: Poems' },
  { author: 'Taban Lo Liyong', title: 'Eating Chiefs' },
  { author: 'Taban Lo Liyong', title: 'Frantz Fanon\'s Uneven Ribs: Poems More and More' },
  { author: 'Taha Hussein', title: 'An Egyptian Childhood' },
  { author: 'Tawfiq Hakim', title: 'Fate of a Cockroach: Four Plays of Freedom' },
  { author: 'Tayeb Salih', title: 'The Wedding of Zein' },
  { author: 'Timothy Wangusa', title: 'Upon This Mountain' },
  { author: 'Tom Mboya', title: 'The Challenge of Nationhood: A Collection of Speeches and Writings' },
  { author: 'Ulli Beier', title: 'Political Spider: An Anthology of Stories From Black Orpheus' },
  { author: 'Véronique Tadjo', title: 'As the Crow Flies' },
  { author: 'W. P. B. Botha', title: 'The Reluctant Playwright' },
  { author: 'W. P. B. Botha', title: 'Wantok' },
  { author: 'William Conton', title: 'The African' },
  { author: 'Williams Sassine', title: 'Wirriyamu' },
  { author: 'Yambo Ouologuem', title: 'Bound to Violence: A Novel' },
  { author: 'Yaw M. Boateng', title: 'The Return' },
  { author: 'Yulisa Amadu Pat Maddy', title: 'No Past No Present No Future' },
  { author: 'Yulisa Amadu Pat Maddy', title: 'Obasai and Other Plays' },
  { author: 'Yusuf Idris', title: 'The Cheapest Nights and Other Stories' },
  { author: 'Yvonne Vera', title: 'Opening Spaces: Contemporary African Women\'s Writing' },
];

// Build the library with generated IDs and filenames
const library: BookMeta[] = rawBooks.map((b) => ({
  id: slugify(b.title),
  title: b.title,
  author: b.author,
  filename: toFilename(b.author, b.title),
  ...(b.coverImage ? { coverImage: b.coverImage } : {}),
}));

// Handle duplicate IDs by appending index
const seen = new Map<string, number>();
for (const book of library) {
  const count = seen.get(book.id) || 0;
  if (count > 0) {
    book.id = `${book.id}-${count}`;
  }
  seen.set(book.id.replace(/-\d+$/, ''), count + 1);
}

export function getLibrary(): BookMeta[] {
  return library;
}

export function getBookById(id: string): BookMeta | undefined {
  return library.find((b) => b.id === id);
}

export function getBookUrl(book: BookMeta): string {
  return `/books/${book.filename}`;
}
